### ISSUE TITLE
Export the escape and unescape functions?

### ISSUE THREAD

**Issue by HEnquist** [chbrown/rfc6902#101]
Thanks for this nice library! 
Would you consider exporting the escape and unescape functions (from pointer.ts)?
Especially unescape would be helpful, to be able to get back the original paths with an "official" function.

**Comment by chbrown** [comment]
Yeah that makes sense, since `Pointer` publicly exposes its `tokens` property. (Maybe it shouldn't have but too late now.)

I will probably rename them to `escapeToken` and `unescapeToken` first though.

Do you have thoughts/opinions on whether they should be reexported from the top-level `index.ts` too? I kind of don't like the feel of that, idk.

**Comment by HEnquist** [comment]
Great! I don't see any need for reexporting them from index.

**Comment by chbrown** [comment]
Ok, now exported in `5.1.2` :)

**Comment by HEnquist** [comment]
Great! Thanks a lot :)
