### ISSUE TITLE
createPatch on Array does not produce accurate patch

### ISSUE THREAD

**Issue by CYDVici0us** [chbrown/rfc6902#12]
Creating a patch on an array, the array order is not respected and the New output does not patch the output using the Patch:

Original Input JSON:
```
{
  "name": "ABC",
  "repositories": [
    "a",
    "e"
  ]
}
```

New Output JSON:
`{
  "name": "ABC",
  "repositories": [
    "a",
    "b",
    "c",
    "d",
    "e"
  ]
}`

Creates Patch:
```
[
  {
    "op": "add",
    "path": "/repositories/1",
    "value": "b"
  },
  {
    "op": "add",
    "path": "/repositories/-",
    "value": "c"
  },
  {
    "op": "add",
    "path": "/repositories/-",
    "value": "d"
  }
]
```

Patched Output:
```
{
  "name": "ABC",
  "repositories": [
    "a",
    "b",
    "e",
    "c",
    "d"
  ]
}
```
The repositories should be in the correct order of the "New Output" above:  a,b,c,d,e.
Confirmed via the Web App:

![screenshot 2016-08-11 09 04 57](https://cloud.githubusercontent.com/assets/5520384/17595668/c16c9764-5fa2-11e6-8cb8-48b9077bf1fb.png)

**Comment by chbrown** [comment]
Good catch. Thanks, fixed.

I initially thought it was going to be trickier, but it turns out I was already keeping track of incremental input/output (length) modifications in the `dist()` function in `diff.ts` — the bug was that I wasn't using it when comparing the cursor index to the length of the input array. So the fix was as simple as `input_length` -> `input_length + padding`.

**Comment by CYDVici0us** [comment]
I appreciate the quick turn around!  I am glad it was a simple correction.
