### ISSUE TITLE
"/"s in path pointers invalidates otherwise valid JSON

### ISSUE THREAD

**Issue by Magnymbus** [chbrown/rfc6902#20]
For example, in a "garden.biome" json file, it says "Invalid JSON: Unexpected token / in JSON at position 1184" where that section reads   

"weather" : [
    [0, [
      "/weather.config:garden" <- The "/" in here is the problem
    ]]
  ],

This is not unexpected behavior, as these are all over starbound's JSONs. Appologies if this is just a special case dealt with by custom code within Starbound's engine.

**Comment by chbrown** [comment]
Glad you were able to clear it up on your own; but perhaps you can expand on what the issue was, in case others with the same problem arrive here via Google search? For instance, I can't tell whether you were trying to use that string as a JSON pointer, or were trying to find that value with a JSON pointer, or what. And what's the "infamous comment incompatibility"?

**Comment by Magnymbus** [comment]
Oh, that was pointing to another file, and the "infamous comment incompatibility" is just that this tool is known for throwing "invalid JSON" when the file includes comment tags ("//Your comment here")
