### ISSUE TITLE
createPatch - Removing array entries 

### ISSUE THREAD

**Issue by kevinfairclough** [chbrown/rfc6902#21]
Is there a particular reason that when deleting array elements that the index is duplicated and individual operations must be applied sequentially to be correct?

`createPatch( ['A','B','C'], ['A']`)
```
result = [
{op: "remove": path: "/arr/1" },
{op: "remove": path: "/arr/1" }
]
```
I am trying to persist the all the patches in one operation to MongoDB.   I assumed the patch would have been

```
result = [
{op: "remove": path: "/arr/2" },
{op: "remove": path: "/arr/1" }
]
```

**Comment by chbrown** [comment]
You could rewrite `diff.diffArrays` to produce the result you assumed you would have gotten. In fact, an earlier (broken) implementation did just that, since I too initially thought the patches that worked from the end made more sense. You could even write a 'middle-out' version if you're feeling particularly masochistic 😆 

But I found that working backwards from the end required more convoluted index tracking, so it behaves the way it currently does because the strict left-to-right ordering is easier to reason about, in my opinion.

You have to pick something, though. There's no way (that I know of) to produce a RFC-6902 JSON patch document with commutable operations. That's not something the spec was built for; a system supporting commutative patches is [far from trivial](https://en.wikibooks.org/wiki/Understanding_Darcs/Patch_theory). But JS is an imperative language, so imperative patching for JSON makes a lot of sense.

See #3, #4, #5, and #12 for issues related to this design choice, and for edge cases demonstrating how previous implementations of the `diffArrays` function kept stepping on / tripping over their own toes.

**Comment by kevinfairclough** [comment]
Thanks for the reply,

For information, mainly if others stumble across this.

With this implementation it is not possible to apply the patch array to MongoDB in one atomic update operation.

Mainly due to 
```
[ 
{op': 'remove', path: '/array/1'},
{op: 'add', path: '/array/-'}
]
```

Would result in $push and $unset of **array** which is invalid in MongoDB.

Other implementations handle arrays differently thus allowing the patch to be applied atomically to MongoDB i.e. [fast-json-patch](https://github.com/Starcounter-Jack/JSON-Patch).  This however adjusts the entire array by issuing replaces (not optimal but works) 

If '/-' was implemented differently (maybe optionally) then i think this would be possible, i.e. if appends had the index instead of '-', don't know if this is even feasible?

With this implementation I would need to use ordered bulk and do each patch/update individually in order (not atomic). It could also be done by getting the object again applying patch and updating the entire document, i.e. replacing it. 

Thanks
Kevin
