### ISSUE TITLE
rfc6902 js file fail to assign to var window

### ISSUE THREAD

**Issue by Emmachen** [chbrown/rfc6902#23]
Hi guys:

There is a check in rfc6902.js: else if(typeof define==="function"&&define.amd){define([],f)}
Once you checked the define is a function then you will not assign correct value to var window, I wonder why you do this check?

Best
Vicky

**Comment by chbrown** [comment]
That is an artifact of the [browserify](https://github.com/browserify/browserify) build process. Basically, it detects whether your environment is using [AMD](http://requirejs.org/docs/whyamd.html#amd), and if so, loads the various submodules using that standard/API.

If your environment defines a global function named `define` and that `define` function has a property named `amd`, you should probably be playing by AMD's rules. I.e., instead of `window.rfc6902.createPatch({id: '1'}, {id: '2'})`, you'd have to work with the AMD (require.js) API [like so](https://jsfiddle.net/xtqvaxLr/7/):

```javascript
require.config({paths: {rfc6902: 'https://cdn.rawgit.com/chbrown/rfc6902/v1.3.0/rfc6902'}})

require(['rfc6902'], function(rfc6902) {
  var patch = rfc6902.createPatch({id: '1'}, {id: '2'})
  // ...
})
```

But more generally, and particularly if you're having issues with this pre-built file, I would recommend using a package manager like [npm](https://www.npmjs.com/package/npm) and your own bundler tool, such as browserify, [webpack](https://webpack.js.org/), [rollup](https://rollupjs.org/), etc., rather than loading `rfc6902.js` or `rfc6902.min.js` directly.

I'm closing this issue, but I would accept a Pull request that updates the build process to a new version of browserify or webpack that handles more use cases (including, presumably, yours).
