### ISSUE TITLE
String value?!

### ISSUE THREAD

**Issue by vporoshok** [chbrown/rfc6902#25]
Why in typescript definitions Operation.value typed as string? By RFC it must be specified as any:

>  For example:
>   { "op": "add", "path": "/a/b/c", "value": [ "foo", "bar" ] }

https://tools.ietf.org/html/rfc6902#section-4.1 page 4

**Comment by chbrown** [comment]
Thanks, you're right, `value` should have type `any` for each of `AddOperation`, `ReplaceOperation`, and `TestOperation`!

I'm surprised this hasn't come up before; I guess I (and others) primarily use the library from a JavaScript client, so I hadn't hit that type-checking snag before.

Fixed by b5dc27c and will shortly publish `v2.2.2` to npm.

**Comment by vporoshok** [comment]
Thank you! We use Angular4 and TypeScript. A lot of my friends are using TypeScript with React. So it's beginning =)
