### ISSUE TITLE
createPatch generates exception with undefined array items

### ISSUE THREAD

**Issue by bozzaj** [chbrown/rfc6902#34]
Example:
```
const obj1 = [3, 4];
const obj2 = [3, 4];
delete obj2[0];

rfc6902.createPatch(obj1, obj2);
```

Exception:
```
Uncaught RangeError: Maximum call stack size exceeded
    at compare (rfc6902.js:316)
    at dist (rfc6902.js:121)
    at dist (rfc6902.js:123)
    at dist (rfc6902.js:123)
    at dist (rfc6902.js:123)
    at dist (rfc6902.js:123)
    at dist (rfc6902.js:123)
    at dist (rfc6902.js:123)
    at dist (rfc6902.js:123)
    at dist (rfc6902.js:123)
```

Other implementations generate this patch:
```
[{"op":"remove","path":"/0"}]
```

**Comment by bozzaj** [comment]
I do understand the difference between delete and splice. However, should it be expected that this library generate an exception and fail in this case?

**Comment by epistemex** [comment]
Ah, I see now, these are intended more as test cases? in any case, aren't they a bit contrived/constructed to fail if so - you would not use such code in production? I agree though, the lib. should perhaps be able to at least catch the error. But..

**Comment by chbrown** [comment]
7122648 averts the stack overflow (oops!), and produces a viable patch:
```js
[{op: 'replace', path: '/0', value: undefined}]
```
But it still doesn't get the semantics completely right w.r.t. `null`/`undefined` array elements, which is kind of tricky (as noted in #35 for object values, rather than array elements). In line with JSON semantics, the patch should probably have `value: null`, since JSON serialization emits `null` for Array elements that have been deleted (or set to `undefined`/`null`):
```js
const obj2 = [3, 4]
delete obj2[0] // or obj2[0] = undefined // or obj2[0] = null
JSON.stringify(obj2)
//=> "[null,4]"
```
I consider the patch generated by "other implementations" to be, well, wrong. At least in Node.js, after running the snippet above, `obj2.length` evaluates to `2`, and the expressions `Array.from(obj2)` and `[...obj2]` both evaluate to 2-item arrays with a first element of `undefined`. The semantics of the `[{"op":"remove","path":"/0"}]` patch preserve none of this behavior; rather, that patch would be what I would expect after running `obj2 = obj2.filter(_ => _)` or `obj2 = obj2.slice(1)`.

I'm still thinking it through, but it seems like an Array's deleted (or otherwise `undefined`) elements, should be treated as if they were `null`, as they would appear after a roundtrip through JSON. This interpretation is akin to the proper treatment of object values that are `undefined` (see discussion in #35), which are completely dropped during a JSON roundtrip. Follow-up at #36.

**Comment by bdsbuild2** [comment]
The issue of null vs undefined in Arrays has always been an odd one to me, but I understand (kind of) why it was implemented that way. Treating "deleted" Array elements as null would be a good compromise. This would preserve the length of the Array. It seems that it would also preserve the Array order as well.

I agree that the other implementations weren't a great solution either.

Thanks for the followup!
