### ISSUE TITLE
Export Pointer class from module

### ISSUE THREAD

**Issue by mmiller42** [chbrown/rfc6902#45]
It would be useful to be able to import the Pointer class so that we can easily parse JSON pointers to token arrays as well.

**Comment by chbrown** [comment]
Please note that you can import and use `Pointer` like:
```js
const {Pointer} = require('rfc6902/pointer')
Pointer.fromJSON('/a/b')
//=> Pointer { tokens: [ '', 'a', 'b' ] }
```
I think it's important to keep the surface area of the root-level module small (currently only three exports) and relevant (all of which are specific to RFC 6902). Since JSON Pointers are defined in RFC 6901, and not required to use the root-level imports, I don't think they belong in the root module. But if you have a compelling use-case in mind, I _could_ be persuaded. Or perhaps it'd suffice to add a couple lines like the snippet above to the documentation (i.e., `README.md`)?

**Comment by mmiller42** [comment]
Thanks! I think adding that other modules are exported besides the entry point to the docs would be useful. I should've checked the dist folder.
