### ISSUE TITLE
offer a /dist/ with precompiled "for the browser" versions?

### ISSUE THREAD

**Issue by Pomax** [chbrown/rfc6902#62]
As ubiquitous as it might feel, there are still plenty of projects without babel or webpack, for whom it would be quite nice to have a standard `/dist/` dir from which to serve (or copy and serve) the library for the browser. Especially when working with simple do moderately complex client/server code in which the client synchronisation relies on patches rather than full state transfers, not needing to install a transpiling and minimizing bundler just to be able to run `applyPatch` would be super valuable.

**Comment by chbrown** [comment]
You mean like <https://github.com/chbrown/rfc6902/tree/master/dist>?

**Comment by Pomax** [comment]
Maybe, I'm mostly looking at what I get after running `npm install` and the result there is a flat dir with no `dist` in it at all O_o

![image](https://user-images.githubusercontent.com/177243/60549120-c4caba00-9cd8-11e9-9690-a5e6952ead71.png)

**Comment by Pomax** [comment]
Ah.... https://github.com/chbrown/rfc6902/blob/master/.npmignore#L5 would be why. Can that line be removed and a patch version pushed to npm?

**Comment by chbrown** [comment]
Done. The npm package includes `dist/*.js` as of `v3.0.3`, and I have recompiled the latest sources (i.e., `v3.0.3`) into `dist/` and released that as `v3.0.4`.

I was surprised at how many projects do this, I guess because I rarely look into `node_modules/*/` unless I'm trying to find a specific bit of source code. I sampled a couple cross-platform libraries (`immutable`, `redux`, `d3`) and they all included `/dist/*.js` builds in their npm package. Hard to argue with that.

Still strikes me as kinda weird that you'd use `npm` to install something, and then not run it with Node.js or else use a bundler like webpack / rollup / etc... but then, what do I know? :) JS is a jungle. Who knows what people will do.

**Comment by Pomax** [comment]
awesome, thanks so much!

As for why: NPM used to bill itself as the "node package manager", but people quickly realized that having to use npm _and_ bower was really weird. Using one tool to pull down the code was much nicer, and so NPM rebranded itself to "not just node package manager" and it's been a little easier to use for full stack ever since.
