### ISSUE TITLE
Removing property in array element is reported as replacing the whole element

### ISSUE THREAD

**Issue by epoberezkin** [chbrown/rfc6902#9]
instead of removing a single property

**Comment by chbrown** [comment]
Ooh, good catch. Fixed in f48ff35 ~= v1.1.2. (Please reopen if your use case is not recursing properly?)

Also brings up an interesting idea of maybe changing the Levenshtein algorithm cost based on whether a small part has changed vs. the whole entry, but that's probably incurs more complexity than it's worth.

**Comment by chbrown** [comment]
Err, make that v1.1.3 (I forgot I had `{..., main: './rfc6902.js'}` in my `package.json` and versioned/built in the wrong order).

**Comment by epoberezkin** [comment]
Thanks!
